WITH TRANSACTIONS_SRC AS (
    SELECT 
        TO_TIMESTAMP_TZ(TRANS_DATE, 'YYYY-MM-DD"T"HH24:MI:SS+TZH:TZM') as TRANS_DATE,
        FAMILY_NAME,
        CAST(AMOUNT AS FLOAT) AS AMOUNT
    FROM {{ source('donors_schema', 'transactions_norm') }}
),

TRANSACTIONS_AGG AS ( 
    SELECT 
        FAMILY_NAME,
        SUM(AMOUNT) AS MONETARY,
        COUNT(AMOUNT) AS FREQUENCY,
        MIN(TRANS_DATE) AS DONATION_START_DATE,
        MAX(TRANS_DATE) AS LAST_DONATION_DATE,
        ROUND(AVG(AMOUNT), 2) AS MEAN_AMOUNT,
        MEDIAN(AMOUNT) AS MED_AMOUNT,
        MAX(AMOUNT) AS MAX_AMOUNT,
        MIN(AMOUNT) AS MIN_AMOUNT,

        CASE 
            WHEN FREQUENCY > 1 THEN TRUE 
            ELSE FALSE 
            END AS IS_RECURRING,
        
        DATEDIFF('day', LAST_DONATION_DATE, CURRENT_TIMESTAMP()) as RECENCY
    FROM TRANSACTIONS_SRC
    GROUP BY FAMILY_NAME 
)

SELECT 
    d.*,
    t.* EXCLUDE(FAMILY_NAME)
FROM {{ source('donors_schema', 'donors_norm') }} d
RIGHT JOIN TRANSACTIONS_AGG t 
    ON d.FAMILY_NAME = t.FAMILY_NAME

