CREATE OR REPLACE DATABASE DONORS;

CREATE OR REPLACE SCHEMA DONORS.DONORS_SCHEMA;

CREATE OR REPLACE TABLE DONORS.DONORS_SCHEMA.DONORS_RAW (
  DONOR_TYPE VARCHAR,
  FAMILY_NAME VARCHAR,
  EMAIL VARCHAR,
  ADDRESS_LINE_1 VARCHAR,
  ADDRESS_LINE_2 VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  POSTAL_CODE VARCHAR,
  COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE DONORS.DONORS_SCHEMA.DONORS_NORM (
  DONOR_TYPE VARCHAR,
  FAMILY_NAME VARCHAR,
  EMAIL VARCHAR,
  ADDRESS_LINE_1 VARCHAR,
  ADDRESS_LINE_2 VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  POSTAL_CODE VARCHAR,
  COUNTRY VARCHAR
);

CREATE OR REPLACE TABLE DONORS.DONORS_SCHEMA.TRANSACTIONS_RAW (
  TRANS_DATE VARCHAR,
  FAMILY_NAME VARCHAR, 
  RECURRING VARCHAR,
  DESCRIPTION VARCHAR,
  AMOUNT FLOAT,
  CURRENCY_TYPE VARCHAR
);

CREATE OR REPLACE TABLE DONORS.DONORS_SCHEMA.TRANSACTIONS_NORM (
  TRANS_DATE VARCHAR,
  FAMILY_NAME VARCHAR, 
  RECURRING VARCHAR,
  DESCRIPTION VARCHAR,
  AMOUNT FLOAT,
  CURRENCY_TYPE VARCHAR
);

