CREATE OR REPLACE TABLE DONORS.DONORS_SCHEMA.NAMENORMALIZATION (
  RAW_NAME VARCHAR,
  CANONICAL_NAME VARCHAR,
  REASON VARCHAR,
  RAW_EMAIL VARCHAR,
  PAYMENT_TYPE VARCHAR
);

TRUNCATE TABLE DONORS.DONORS_SCHEMA.NAMENORMALIZATION;

-- Donor metadata intentionally excluded for privacy purposes
INSERT INTO DONORS.DONORS_SCHEMA.NAMENORMALIZATION
(RAW_NAME, CANONICAL_NAME, REASON, RAW_EMAIL, PAYMENT_TYPE) 
VALUES ... ;

SELECT * FROM DONORS.DONORS_SCHEMA.NAMENORMALIZATION;
